wandb_version: 1

Data_set:
  desc: null
  value: Cifar100
N_cabeças:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1677456934.180853
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.8
      5: 0.13.9
      8:
      - 1
      - 5
architecture:
  desc: null
  value: Resnet18 Hydra
epocas:
  desc: null
  value: 100
