wandb_version: 1

Data_set:
  desc: null
  value: Cifar 100
N_ensemble:
  desc: null
  value: '8'
_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1676892886.905655
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.8
      5: 0.13.9
      8:
      - 1
      - 5
architecture:
  desc: null
  value: Resnet18
temperatura:
  desc: null
  value: 4
